spring.application.name=ProyectoProgra4
server.port=${PORT:8080}

app.name=BolsaEmpleo
app.default-currency=CRC
app.tax-rate=0.13

spring.datasource.url=jdbc:postgresql://localhost:5433/proyectoProgra4_DB
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true